config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'comments/index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  namespace :admin do
    resources :genres
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index]
    resources :comments, only: [:index]
    patch ':id/withdraw' => 'users#withdraw', as: 'withdraw_user'
    patch ':id/invalid' => 'posts#invalid', as: 'invalid_post'
    patch ':id/invalid' => 'comments#invalid', as: 'invalid_comment'
  end

  namespace :posts do
    resources :searches, only: :index, defaults: { format: :json }
  end

  resources :posts, only: [:index, :new, :create, :destroy, :show] do
    resource :post_assessments, only: [:create, :destroy]
    resource :post_negative_assessments, only: [:create, :destroy]
    resources :comments, only: [:update, :create, :destroy, :new] do
      resource :comment_assessments, only: [:create, :destroy]
      resource :comment_negative_assessments, only: [:create, :destroy]
    end
  end

  resources :users, only: [:show, :edit, :update] do
    collection do
      patch 'hide'
      get 'confirm'
    end
  end

  resources :genres, only: [:show, :index]

  resources :inquiries, only: [:new, :create]
  post 'inquiries/confirm', to: 'inquiries#confirm', as: 'confirm'
  post 'inquiries/back', to: 'inquiries#back', as: 'back'
  get 'done', to: 'inquiries#done', as: 'done'

  root :to => 'homes#top'
  get 'homes/about'
  get 'news/data'

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post
  belongs_to :user
  has_many :comment_assessments, dependent: :destroy
  has_many :comment_negative_assessments, dependent: :destroy

  validates :body, presence: true

  def comment_favorited_by?(user)
    comment_assessments.where(user_id: user.id).exists?
  end

  def comment_negative_assessment_by?(user)
    comment_negative_assessments.where(user_id: user.id).exists?
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @comments = Comment.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def invalid
    @comment = Comment.find(params[:id])
    @comment.update(is_valid: false)
    redirect_to admin_posts_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.score = Language.get_data(comment_params[:body])  #natural language score用
    @comment.user_id = current_user.id
    @comment.post_id = @post.id

      respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js { @status = "success" }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js { @status = "fail" }
      end
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    if comment.destroy
      flash[:notice] = "Comment was successfully destroyed."
      redirect_to post_path(comment.post_id)
    else
      render template: "posts/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id,:post_id,:body)
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container">
  <h5 class="ml-4 my-4 bg-light d-inline-flex">Comment一覧</h5>
  <div class="row justify-content-center mb-5">
    <div class="col-md-12">
      <table class="table table-hover">
        <thead class="table-secondary">
          <tr>
            <th>コメント者<br>id</th>
            <th>コメント者名<br>(NickName)</th>
            <th>コメント時間</th>
            <th>コメント内容</th>
            <th>コメント先<br>(Post Id No.)</th>
            <th>AI分析結果</th>
            <th>状態</th>
            <td></td>
          </tr>
        </thead>
        <tbody>
          <% @comments.each do |comment| %>
            <tr>
              <td><%= link_to admin_user_path(comment.user_id), method: :get do %><%= comment.user.id %><% end %></td>
              <td><%= link_to admin_user_path(comment.user_id), method: :get do %><%= comment.user.nick_name %><% end %></td>
              <td><%= comment.created_at.to_s(:datetime_jp) %></td>
              <td><%= comment.body %></td>
              <td><%= comment.post_id %></td>
              <td><%= comment.score %></td>
              <td>
                <% if comment.is_valid == false %>
                  <p class="text-danger">削除済み</p>
                <% else %>
                  <p class="text-success">有効</p></td>
                <% end %>
              </td>
              <td>
                <% if comment.is_valid == false %>
                  <p>強制削除済み</p>
                <% else %>
                  <%= link_to "削除する", admin_invalid_comment_path(comment), method: :patch, class: "btn btn-lg, btn-danger", data:
                    { confirm: "本当に削除しますか?", cancel: "Cancel", commit: "Delete"}, title: "Confirmation" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @comments %>
    </div>
  </div>
</div>