config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'comments/index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  namespace :admin do
    resources :genres
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index]
    resources :comments, only: [:index]
    patch ':id/withdraw' => 'users#withdraw', as: 'withdraw_user'
    patch ':id/invalid' => 'posts#invalid', as: 'invalid_post'
    patch ':id/invalid' => 'comments#invalid', as: 'invalid_comment'
  end

  namespace :posts do
    resources :searches, only: :index, defaults: { format: :json }
  end

  resources :posts, only: [:index, :new, :create, :destroy, :show] do
    resource :post_assessments, only: [:create, :destroy]
    resource :post_negative_assessments, only: [:create, :destroy]
    resources :comments, only: [:update, :create, :destroy, :new] do
      resource :comment_assessments, only: [:create, :destroy]
      resource :comment_negative_assessments, only: [:create, :destroy]
    end
  end

  resources :users, only: [:show, :edit, :update] do
    collection do
      patch 'hide'
      get 'confirm'
    end
  end

  resources :genres, only: [:show, :index]

  resources :inquiries, only: [:new, :create]
  post 'inquiries/confirm', to: 'inquiries#confirm', as: 'confirm'
  post 'inquiries/back', to: 'inquiries#back', as: 'back'
  get 'done', to: 'inquiries#done', as: 'done'

  root :to => 'homes#top'
  get 'homes/about'
  get 'news/data'

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments
  has_many :post_assessments, dependent: :destroy
  has_many :post_negative_assessments, dependent: :destroy

  enum genre_id: { 公共交通: 0, インフラ: 1, ヘルスケア: 2, 生活: 3, 地域: 4, その他: 5}
  enum generation: { "年代を選択してください":0, '10代': 1, '20代': 2, '30代': 3, '40代': 4, '50代': 5, '60代': 6, '70歳以上': 7 }

  validates :title,
      :body,
      :genre_id,
      presence: true

  def post_favorited_by?(user)
    post_assessments.where(user_id: user.id).exists?
  end

  def post_negative_assessment_by?(user)
    post_negative_assessments.where(user_id: user.id).exists?
  end

  def comment_favorited_by?(user, comment)
    comment_assessments.where(user_id: user.id, comment_id: comment.id).exists?
  end

  def comment__negative_assessment_by?(user, comment)
    comment_negative_assessments.where(user_id: user.id, comment_id: comment.id).exists?
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def invalid
    @post = Post.find(params[:id])
    @post.update(is_valid: false)
    redirect_to admin_posts_path
  end
end

app/controllers/posts/searches_controller.rb
class Posts::SearchesController < ApplicationController
  def index

    @posts = Post.where('title LIKE(?)', "%#{params[:title]}%").first(5)
    respond_to do |format|
      format.html { redirect_to :root }
        # ↓検索結果のデータをレスポンスするコード
      format.json { render json: @posts }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [ :index]

  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
    posts = Post.where(created_at: 1.week.ago.beginning_of_day..Time.zone.now.end_of_day)
    @favorites = posts.where(id: PostAssessment.group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
    if user_signed_in?
     @user = User.find(current_user.id)
    end
  end

  def new
    @post = Post.new
    @genres = Genre.all
  end

  def create
    @post = Post.new(post_params)
    @post.score = Language.get_data(post_params[:body])  #natural language score用
    @post.generation = current_user.generation
    @post.is_valid = false

      respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Cooment was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.js { @status = "success" }
        flash[:notice] = "Post was successfully created."
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js { @status = "fail" }
      end
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:notice] = "Post was successfully destroyed."
      redirect_to posts_path
    else
      render "index"
    end
  end

  def search
    respond_to do |format|
      format.html
      format.json
      # json形式で値を返し、jbundlerファイルを使用できるようになる
    end
  end

  def show
    @post = Post.find(params[:id])
    @posts = Post.all.order(created_at: :desc)
    @comments = @post.comments
    posts = Post.where(created_at: 1.week.ago.beginning_of_day..Time.zone.now.end_of_day)
    @favorites = posts.where(id: PostAssessment.group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
    @user = User.find(current_user.id)
  end

  def post_params
    params.require(:post).permit(:title, :body, :genre_id, :user_id)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="modal-dialog modal-dialog-scrollable" role="document">
  <div class="modal-content">
    <%= form_with(model: @post, remote: true) do |f| %>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
        <div class="modal-header">
          <h5 class="modal-title">NewPost</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="modal-body">
          <div class="form-group field">
            <%= f.select :genre_id, Genre.genres.keys, {prompt: "選択してください"} %>
            <%= f.text_field :title, class: "form-control", placeholder:"Title" %>
            <br>
            <%= f.text_area :body, class: "form-control", placeholder:"Post here" %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
          </div>
        </div>
        <div class="modal-footer actions">
          <%= f.submit "送信する", class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<% posts.last(0).each do |post| %>
  <li class="post">
      <%= link_to post_path(post), method: :get do %>
        <%= post.title %>
      <% end %>
  </li>
<% end %>

app/views/posts/_show.html.erb
<div id="comment-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="post-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<!--投稿カード部分-->
<div class="modal-dialog modal-dialog-scrollable modal-dialog-fluid" role="document">
  <div class="modal-content">
    <div class="card-body">
      <div class="row main">
        <div class="col post mx-auto">
          <div class="card-list-containar py-1">
            <div class="card w-auto mx-auto shadow-lg">
              <div class="modal-header">
                <h2 class="modal-title text-center mt-1">PostShow</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>

              <div class="row card-body">
                <div class="col-2">
                  <%= link_to user_path(@post.user_id), method: :get do %>
                    <%= attachment_image_tag @post.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", style: "border-radius:50%;}" %>
                  <% end %>
                </div>
                <div class="col-10">
                  <div class="row mb-2">
                    <div class="col-lg-4 fas fa-user"><%= @post.user.nick_name %></div>
                    <div class="col-lg-4"><%= @post.genre_id %></div>
                    <div class="col-lg-4"><%= @post.created_at.to_s(:datetime_jp) %></div>
                  </div>
                  <div class="row mb-2">
                    <div class="col-lg-12">タイトル：<%= @post.title %></div>
                    <div class="col-lg-12">投稿：<%= @post.body %></div>
                  </div>
                    <div class="row mb-2">
                    <% if user_signed_in? %>
                    <div class="col-lg-3" id="post_assessment_<%= @post.id %>">
                      <!--部分テンプレートでいれる-->
                      <%= render 'post_assessments/post_assessment', post: @post%>
                      <!--部分テンプレート終わり-->
                    </div>
                      <% else %>
                    <div class="col-lg-3">
                      <p>
                        ♥<%= @post.post_assessments.count %> いいね
                      </p>
                    </div>
                      <% end %>
                      <% if user_signed_in? %>
                    <div class="col-lg-3" id="post_negative_assessment_<%= @post.id %>">
                      <!--部分テンプレートでいれる-->
                      <%= render 'post_negative_assessments/post_negative_assessment', post: @post%>
                      <!--部分テンプレート終わり-->
                    </div>
                      <% else %>
                    <div class="col-lg-3">
                      <p class="far fa-meh">
                        ★<%= @post.comment_assessments.count %>うーん
                      </p>
                    </div>
                      <% end %>
                    <div class="col-lg-3">
                      <%= link_to post_path(@post), method: :get do %>
                      <div>コメント数：<%= @post.comments.count %></div>
                      <% end %>
                    </div>
                    <div class="col-lg-3">
                      <%= link_to "コメントする", new_post_comment_path(@post), remote: true, class: "btn btn-lg, btn-primary" %>
                    </div>
                  </div>
                </div>
              </div>
              <!--ここからコメント-->
              <h3 class="blog-heading text-center mt-3">PostComment</h3>

              <% @comments.last(10).each do |comment| %>
              <div class="row comment-card-body">

                <div class="col-2">
                  <%= link_to user_path(comment.user_id), method: :get do %>
                    <%= attachment_image_tag comment.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", style: "border-radius:50%;}" %>
                  <% end %>
                </div>

                <div class="col-10">
                  <div class="row mb-2">
                    <div class="col-lg-4 fas fa-user"><%= comment.user.nick_name %></div>
                    <div class="col-lg-4"></div>
                    <div class="col-lg-4"><%= comment.created_at.to_s(:datetime_jp) %></div>
                  </div>
                  <div class="row mb-2">
                    <div class="col-lg-12">コメント：<%= comment.body %></div>
                  </div>
                      <div class="row mb-2">
                    <% if user_signed_in? %>
                    <div class="col-lg-3" id="comment_assessment_<%= comment.id %>">
                      <!--部分テンプレートでいれる-->
                      <%= render 'comment_assessments/comment_assessment', comment: comment, post: @post %>
                      <!--部分テンプレート終わり-->
                    </div>
                      <% else %>
                    <div class="col-lg-3">
                      <p>
                        ♥<%= comment.comment_assessments.count %> いいね
                      </p>
                    </div>
                      <% end %>
                      <% if user_signed_in? %>
                        <div class="col-lg-3" id="comment_negative_assessment_<%= comment.id %>">
                          <!--部分テンプレートでいれる-->
                          <%= render 'comment_negative_assessments/comment_negative_assessment', comment: comment, post: @post %>
                          <!--部分テンプレート終わり-->
                        </div>
                      <% else %>
                    <div class="col-lg-3">
                      <p class="far fa-meh">
                        <%= @post.comment_assessments.count %>うーん
                      </p>
                    </div>
                      <% end %>
                    <div class="col-lg-3">
                    </div>
                    <% if user_signed_in? %>
                    <div class="col-lg-3">
                      <%= link_to "削除する", post_comment_path(@post, comment), method: :delete, class: "btn btn-lg, btn-danger" %>
                    </div>
                    <% else %>
                    <div class="col-lg-3">
                    </div>
                    <% end %>

                  </div>
                </div>
              </div>
              <% end %>
              <div id="comment-append" class="comment-card-body"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="comment-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/posts/_tr.html.erb
<div class="row card-body">
  <div class="col-2">
    <%= attachment_image_tag @post.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", style: "border-radius:50%;}" %>
  </div>

  <div class="col-10">
    <div class="row mb-2">
      <div class="col-lg-3 fas fa-user"><%= link_to user_path(post.user_id), method: :get do %><%= post.user.nick_name %><% end %></div>
      <div class="col-lg-2"></div>
      <div class="col-lg-4"><%= post.created_at.to_s(:datetime_jp) %></div>
      <div class="col-lg-3"><span class="sentiment-score">分析スコア<%= post.score %></span></div>
    </div>

    <div class="row mb-2">
      <div class="col-lg-12">タイトル：<%= post.title %></div>
      <div class="col-lg-12">投稿：<%= post.body %></div>
    </div>

    <div class="row mb-2">
      <% if user_signed_in? %>
        <div class="col-lg-2" id="post_assessment_<%= post.id %>">
          <!--部分テンプレートでいれる-->
          <%= render 'post_assessments/post_assessment', post: post%>
          <!--部分テンプレート終わり-->
        </div>
      <% else %>
        <div class="col-lg-2">
          <p>
            ♥<%= post.post_assessments.count %> いいね
          </p>
        </div>
      <% end %>

      <% if user_signed_in? %>
        <div class="col-lg-2" id="post_negative_assessment_<%= post.id %>">
          <!--部分テンプレートでいれる-->
          <%= render 'post_negative_assessments/post_negative_assessment', post: post%>
          <!--部分テンプレート終わり-->
        </div>
      <% else %>
        <div class="col-lg-2">
          <p class="">
            ★<%= post.post_negative_assessments.count %>うーん
          </p>
        </div>
      <% end %>

      <div class="col-lg-2">
        <%= link_to post_path(post), method: :get do %>
        <div>コメント数：<%= post.comments.count %></div>
        <% end %>
      </div>

      <% if user_signed_in? %>
        <div class="col-lg-3">
          <%= link_to "コメントする", new_post_comment_path(post), remote: true, class: "btn btn-lg, btn-primary" %>
        </div>
      <% else %>
        <div class="col-lg-3">
        </div>
      <% end %>

      <% if user_signed_in? && current_user.id == post.user_id %>
        <div class="col-lg-3">
          <%= link_to "削除する", post_path(post), method: :delete, class: "btn btn-lg, btn-danger", data:
          { confirm: "Are you sure to delete?", cancel: "Cancel", commit: "Delete"}, title: "Confirmation" %>
        </div>
      <% else %>
        <div class="col-lg-3">
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/posts/create.js.erb
<% if @status == 'success' %>
    $("#table-append").append("<%= j(render("tr", post: @post)) %>");
<%  elsif @status == 'fail' %>
    alert('Error Please fill in all contents!');
<% end %>
$("#post-modal").modal("hide");

app/views/posts/index.html.erb
<div id="comment-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="post-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="show-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<!--main-visual部分-->
<%= render 'layouts/mainvisual', post: @posts %>
<!--投稿カード部分-->
<div class="card-body">
  <div class="row main">
    <div class="col-md-9 post">
      <h2 class="blog-heading text-center mt-1">PostTimeLine</h2>
      <div class="card-list-containar py-1">
        <% @posts.last(10).each do |post| %>
        <!--postがadmin側で削除された場合非表示にする-->
        <% if post.is_valid =! false %>
        <div class="card w-auto mx-auto mt-4 shadow-lg scroll-list jscroll">
          <div class="row card-body">
            <div class="col-2 ">
              <%= link_to user_path(post.user_id), method: :get do %>
                <%= attachment_image_tag post.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", style: "border-radius:50%;}" %>
              <% end %>
            </div>
            <div class="col-10">
              <div class="row mb-2">
                <div class="col-lg-3 fas fa-user"><%= link_to user_path(post.user_id), method: :get do %><%= post.user.nick_name %><% end %></div>
                <div class="col-lg-2"><%= post.genre_id %></div>
                <div class="col-lg-4"><%= post.created_at.to_s(:datetime_jp) %></div>
                <div class="col-lg-3"><span class="sentiment-score">分析スコア<%= post.score %></span></div>
              </div>
              <div class="row mb-2">
                <div class="col-lg-12">タイトル：<%= post.title %></div>
                <div class="col-lg-12">投稿：<%= post.body %></div>
              </div>
              <div class="row mb-2">
                <% if user_signed_in? %>
                  <div class="col-lg-2" id="post_assessment_<%= post.id %>">
                    <!--部分テンプレートでいれる-->
                    <%= render 'post_assessments/post_assessment', post: post%>
                    <!--部分テンプレート終わり-->
                  </div>
                <% else %>
                  <div class="col-lg-2">
                    <p>
                      ♥<%= post.post_assessments.count %> いいね
                    </p>
                  </div>
                <% end %>

                <% if user_signed_in? %>
                  <div class="col-lg-2" id="post_negative_assessment_<%= post.id %>">
                    <!--部分テンプレートでいれる-->
                    <%= render 'post_negative_assessments/post_negative_assessment', post: post%>
                    <!--部分テンプレート終わり-->
                  </div>
                <% else %>
                  <div class="col-lg-2">
                    <p class="">
                      ★<%= post.post_negative_assessments.count %>うーん
                    </p>
                  </div>
                <% end %>

                <div class="col-lg-2" id="comment<%= post.id %>">
                  <%= link_to post_path(post), method: :get do %>
                  <div>コメント数：<%= post.comments.count %></div>
                  <% end %>
                </div>
                <% if user_signed_in? %>
                  <div class="col-lg-3">
                    <%= link_to "コメントする", new_post_comment_path(post), remote: true, class: "btn btn-lg, btn-primary" %>
                  </div>
                <% else %>
                  <div class="col-lg-3">
                  </div>
                <% end %>

                <% if user_signed_in? && current_user.id == post.user_id %>
                  <div class="col-lg-3">
                    <%= link_to "削除する", post_path(post), method: :delete, class: "btn btn-lg, btn-danger", data:
                    { confirm: "Are you sure to delete?", cancel: "Cancel", commit: "Delete"}, title: "Confirmation" %>
                  </div>
                <% else %>
                  <div class="col-lg-3">
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <% else %>
        <% end %>
        <% end %>
        <%= paginate @posts %>
        <div id="table-append" class="card w-auto mx-auto mt-4 shadow-lg"></div>
          </div>
        </div>
      <div class="col-md-3 sidebar border-left">
　　　 <%= render 'layouts/sidebar', post: @posts %>
　　　</div>
  </div>
</div>

app/views/posts/new.html.erb
<h2>New Post Page</h2>
<div class="row">
  <div class="col">
    <h5 class="text-dark bg-light p-4 mb-0">投稿フォーム</h5>
    <%= form_with model: @post, local:true do |f| %>
        <%= f.select :genre_id, Genre.genres.keys.to_a, autocomplete: "ジャンル" %>
        <%= f.text_field :title, class:"form-control", placeholder:"Title" %>
        <%= f.text_area :body, class:"form-control", placeholder:"投稿をここに" %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
    <% end %>
  </div>
</div>

app/views/posts/new.js.erb
$("#post-modal").html("<%= escape_javascript(render 'form') %>")
$("#post-modal").modal("show")

app/views/posts/show.html.erb
<div id="comment-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="post-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<!--main-visual部分-->
<%= render 'layouts/mainvisual', post: @posts %>
<!--投稿カード部分-->
<div class="card-body">
  <div class="row main">
    <div class="col-md-9 post">
      <h2 class="blog-heading text-center mt-1">PostShow</h2>
      <div class="card-list-containar py-1">
        <div class="card w-auto mx-auto shadow-lg">
          <div class="row card-body">
            <div class="col-2">
              <%= link_to user_path(@post.user_id), method: :get do %>
                <%= attachment_image_tag @post.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", style: "border-radius:50%;}" %>
              <% end %>
            </div>
            <div class="col-10">
              <div class="row mb-2">
                <div class="col-lg-3 fas fa-user"><%= link_to user_path(@post.user_id), method: :get do %><%= @post.user.nick_name %><% end %></div>
                <div class="col-lg-2"><%= @post.genre_id %></div>
                <div class="col-lg-4"><%= @post.created_at.to_s(:datetime_jp) %></div>
                <div class="col-lg-3"><span class="sentiment-score">分析スコア<%= @post.score %></span></div>
              </div>
              <div class="row mb-2">
                <div class="col-lg-12">タイトル：<%= @post.title %></div>
                <div class="col-lg-12">投稿：<%= @post.body %></div>
              </div>
                <div class="row mb-2">
                <% if user_signed_in? %>
                <div class="col-lg-2" id="post_assessment_<%= @post.id %>">
                  <!--部分テンプレートでいれる-->
                  <%= render 'post_assessments/post_assessment', post: @post%>
                  <!--部分テンプレート終わり-->
                </div>
                  <% else %>
                <div class="col-lg-2">
                  <p>
                    ♥<%= @post.post_assessments.count %> いいね
                  </p>
                </div>
                  <% end %>
                  <% if user_signed_in? %>
                <div class="col-lg-2" id="post_negative_assessment_<%= @post.id %>">
                  <!--部分テンプレートでいれる-->
                  <%= render 'post_negative_assessments/post_negative_assessment', post: @post%>
                  <!--部分テンプレート終わり-->
                </div>
                  <% else %>
                <div class="col-lg-2">
                  <p class="far fa-meh">
                    ★<%= @post.comment_assessments.count %>うーん
                  </p>
                </div>
                  <% end %>
                <div class="col-lg-2">
                  <%= link_to post_path(@post), method: :get do %>
                  <div>コメント数：<%= @post.comments.count %></div>
                  <% end %>
                </div>
                <div class="col-lg-3">
                  <%= link_to "コメントする", new_post_comment_path(@post), remote: true, class: "btn btn-lg, btn-primary" %>
                </div>
                <% if user_signed_in? && current_user.id == @post.user_id %>
                <div class="col-lg-3">
                  <%= link_to "削除する", post_path(@post), method: :delete, class: "btn btn-lg, btn-danger", data:
                  { confirm: "Are you sure to delete?", cancel: "Cancel", commit: "Delete"}, title: "Confirmation" %>
                </div>
                <% else %>
                <div class="col-lg-3">
                </div>
                <% end %>
              </div>
            </div>
          </div>
          <!--ここからコメント-->
          <h3 class="blog-heading text-center mt-3">PostComment</h3>

          <% @comments.last(10).each do |comment| %>
          <!--commentがadmin側で削除された場合非表示にする-->
          <% if comment.is_valid =! false %>
          <div class="row comment-card-body">

            <div class="col-2">
              <%= link_to user_path(comment.user_id), method: :get do %>
                <%= attachment_image_tag comment.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", style: "border-radius:50%;}" %>
              <% end %>
            </div>

            <div class="col-10">
              <div class="row mb-2">
                <div class="col-lg-3 fas fa-user"><%= link_to user_path(@post.user_id), method: :get do %><%= comment.user.nick_name %><% end %></div>
                <div class="col-lg-2"></div>
                <div class="col-lg-4"><%= comment.created_at.to_s(:datetime_jp) %></div>
                <div class="col-lg-3"><span class="sentiment-score">分析スコア<%= comment.score %></span></div>
              </div>
              <div class="row mb-2">
                <div class="col-lg-12">コメント：<%= comment.body %></div>
              </div>
                  <div class="row mb-2">
                <% if user_signed_in? %>
                <div class="col-lg-3" id="comment_assessment_<%= comment.id %>">
                  <!--部分テンプレートでいれる-->
                  <%= render 'comment_assessments/comment_assessment', comment: comment, post: @post %>
                  <!--部分テンプレート終わり-->
                </div>
                  <% else %>
                <div class="col-lg-3">
                  <p>
                    ♥<%= comment.comment_assessments.count %> いいね
                  </p>
                </div>
                  <% end %>
                  <% if user_signed_in? %>
                    <div class="col-lg-3" id="comment_negative_assessment_<%= comment.id %>">
                      <!--部分テンプレートでいれる-->
                      <%= render 'comment_negative_assessments/comment_negative_assessment', comment: comment, post: @post %>
                      <!--部分テンプレート終わり-->
                    </div>
                  <% else %>
                <div class="col-lg-3">
                  <p class="far fa-meh">
                    <%= @post.comment_assessments.count %>うーん
                  </p>
                </div>
                  <% end %>
                  <div class="col-lg-3">
                  </div>

                  <% if user_signed_in? && current_user.id == comment.user_id %>
                  <div class="col-lg-3">
                    <%= link_to "削除する", post_comment_path(@post, comment), method: :delete, class: "btn btn-lg, btn-danger", data:
                    { confirm: "Are you sure to delete?", cancel: "Cancel", commit: "Delete"}, title: "Confirmation" %>
                  </div>
                  <% else %>
                  <div class="col-lg-3">
                  </div>
                  <% end %>

              </div>
            </div>
          </div>
          <% else %>
          <% end %>
          <% end %>
          <div id="comment-append" class="comment-card-body"></div>
        </div>
      </div>
    </div>
      <div class="col-md-3 sidebar border-left">
　　　 <%= render 'layouts/sidebar', post: @posts %>
　　　</div>
  </div>
</div>

app/views/posts/show.js.erb
$("#show-modal").html("<%= escape_javascript(render 'show') %>")
$("#show-modal").modal("show")