config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'comments/index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  namespace :admin do
    resources :genres
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index]
    resources :comments, only: [:index]
    patch ':id/withdraw' => 'users#withdraw', as: 'withdraw_user'
    patch ':id/invalid' => 'posts#invalid', as: 'invalid_post'
    patch ':id/invalid' => 'comments#invalid', as: 'invalid_comment'
  end

  namespace :posts do
    resources :searches, only: :index, defaults: { format: :json }
  end

  resources :posts, only: [:index, :new, :create, :destroy, :show] do
    resource :post_assessments, only: [:create, :destroy]
    resource :post_negative_assessments, only: [:create, :destroy]
    resources :comments, only: [:update, :create, :destroy, :new] do
      resource :comment_assessments, only: [:create, :destroy]
      resource :comment_negative_assessments, only: [:create, :destroy]
    end
  end

  resources :users, only: [:show, :edit, :update] do
    collection do
      patch 'hide'
      get 'confirm'
    end
  end

  resources :genres, only: [:show, :index]

  resources :inquiries, only: [:new, :create]
  post 'inquiries/confirm', to: 'inquiries#confirm', as: 'confirm'
  post 'inquiries/back', to: 'inquiries#back', as: 'back'
  get 'done', to: 'inquiries#done', as: 'done'

  root :to => 'homes#top'
  get 'homes/about'
  get 'news/data'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  validates :email,
            :nick_name,
            :first_name,
            :family_name,
            :first_name_kana,
            :family_name_kana,
            :occupation,
            :address,
            :encrypted_password,
            :generation,
            :sex,
            presence: true

  has_many :posts, dependent: :destroy
  has_many :post_assessments, dependent: :destroy
  has_many :post_negative_assessments, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :comment_assessments, dependent: :destroy
  has_many :comment_negative_assessments, dependent: :destroy




  enum occupation: { "職業を選択してください":0, 会社員: 1, 経営者: 2, 自営業: 3, フリーター: 4, 学生: 5, その他: 6 }
  enum generation: { "年代を選択してください":0, '10代': 1, '20代': 2, '30代': 3, '40代': 4, '50代': 5, '60代': 6, '70歳以上': 7 }
  enum sex: { "性別を選択してください":0, 男性: 1, 女性: 2 }
  enum address: {
     "都道府県を選択してください":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
  }

  # profile_image用
  attachment :profile_image

  # omniauthのコールバック時に呼ばれるメソッド,Gmailでサインインした時は
  # 　以下の数値をデフォルトで入れておく
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.nick_name = "no name"
      user.first_name = "no name"
      user.family_name = "no name"
      user.first_name_kana = "no name"
      user.family_name_kana = "no name"
      user.occupation = 1
      user.address = 1
      user.phone_number = "no number"
      user.generation = 1
      user.sex = 1
    end
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.order(created_at: :desc).page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @genre_id_hash = { "公共交通" => 0, "インフラ" => 0, "ヘルスケア" => 0, "生活" => 0, "地域" => 0, "その他" => 0 }
    @posts.each do |post|
      @genre_id_hash[post.genre_id] = @genre_id_hash[post.genre_id] + 1
    end
  end

  def update
  end

  def withdraw
    @user = User.find(params[:id])
    @user.update(is_valid: false)
    redirect_to admin_users_path
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
# callback for facebook
  # def facebook
  #   callback_for(:facebook)
  # end

  # # callback for twitter
  # def twitter
  #   callback_for(:twitter)
  # end

  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    #byebug
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    user_path(current_user)
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    UserMailer.with(user: @user).welcome_email.deliver_now
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super UserMailer.with(user: @user).welcome_email.deliver_later
  # end

  # POST /resource/sign_in
  # def create
  #   super UserMailer.with(user: @user).welcome_email.deliver_later
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def reject_inactive_user
    @user = User.find(params[:user][:id])
    if @user
      if @user.valid_password?(params[:user][:id]) && !@user.is_valid
        redirect_to new_user_session_path
      end
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @user_posts = @user.posts.order(created_at: :desc)
    @posts =Post.all.order(created_at: :desc).page(params[:page]).per(10)

    @genre_id_hash = { "公共交通" => 0, "インフラ" => 0, "ヘルスケア" => 0, "生活" => 0, "地域" => 0, "その他" => 0 }
    @posts.each do |post|
      @genre_id_hash[post.genre_id] = @genre_id_hash[post.genre_id] + 1
    end


    @generation_id_hash = {"10代"=> 0, "20代"=> 0, "30代"=> 0, "40代"=> 0, "50代"=> 0, "60代"=> 0, "70歳以上"=> 0 }
    @posts.each do |post|
      @generation_id_hash[post.generation] = @generation_id_hash[post.generation] + 1
    end

    posts = Post.where(created_at: 1.week.ago.beginning_of_day..Time.zone.now)
    @favorites = posts.where(id: PostAssessment.group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
    # @post_today = Post.where(created_at: 1.week.ago.beginning_of_day..Time.zone.now.end_of_day)
    # @post_yesterday = Post.where(created_at: 1.week.ago.beginning_of_day..Time.zone.now.end_of_day)
  end

  def edit
    @user = User.find(params[:id])
  end

  def confirm
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    respond_to do |format|
      if @user.save
        redirect_to user_path(@user)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :created, location: @user }
        format.js { @status = "success" }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js { @status = "fail" }
      end
    end
  end


  def hide
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :occupation, :nick_name, :first_name,
    :first_name_kana, :family_name, :family_name_kana, :address, :phone_number, :email, :sex, :generation, :introduction)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
  <h5 class="ml-4 my-4 bg-light d-inline-flex">User一覧</h5>
  <div class="row justify-content-center mb-5">
    <div class="col-md-12">
      <table class="table table-hover">
        <thead class="table-secondary">
          <tr>
            <th>UserID</th>
            <th>NickName</th>
            <th>性別</th>
            <th>年代</th>
            <th>職業</th>
            <th>住まい</th>
            <th>登録日</th>
            <th>状態</th>
            <td></td>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= link_to admin_user_path(user), method: :get do %><%= user.nick_name %><% end %></td>
              <td><%= user.sex %></td>
              <td><%= user.generation %></td>
              <td><%= user.occupation %></td>
              <td><%= user.address %></td>
              <td><%= user.created_at.to_s(:datetime_jp) %></td>
              <td>
                <% if user.is_valid == false %>
                  <p class="text-danger">退会</p>
                <% else %>
                  <p class="text-success">有効</p></td>
                <% end %>
              </td>
              <td>
                <% if user.is_valid == false %>
                  <p>強制退会済み</p>
                <% else %>
                  <%= link_to "退会させる", admin_withdraw_user_path(user), method: :patch, class: "btn btn-lg, btn-danger", data:
                    { confirm: "本当に退会しますか?", cancel: "Cancel", commit: "Delete"}, title: "Confirmation" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div>
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <h5 class="ml-4 my-4 bg-light d-inline-flex">User詳細</h5>
  <div class="row justify-content-center mb-5">
    <div class="col-md-12">
      <table class="table table-bordered table-hover">
        <thead class="table-secondary">
          <tr>
            <th>UserID</th>
            <th>NickName</th>
            <th>性別</th>
            <th>年代</th>
            <th>職業</th>
            <th>住まい</th>
            <th>登録日</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td><%= @user.id %></td>
              <td><%= @user.nick_name %></td>
              <td><%= @user.sex %></td>
              <td><%= @user.generation %></td>
              <td><%= @user.occupation %></td>
              <td><%= @user.address %></td>
              <td><%= @user.created_at.to_s(:datetime_jp) %></td>
            </tr>
        </tbody>
      </table>
      <table class="table table-bordered table-hover">
        <thead class="table-secondary">
          <tr>
            <th>今週の投稿数</th>
            <th>今月の投稿数</th>
            <th>前月の投稿数</th>
            <th>合計の投稿数</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td><%= @user.posts.count %></td>
              <td><%= @user.posts.count %></td>
              <td><%= @user.posts.count %></td>
              <td><%= @user.posts.count %></td>
            </tr>
        </tbody>
      </table>
    <%= render 'users/chart' %>
    </div>
  </div>
</div>